#!/bin/sh
[ "${1+1}" ] || exec csh -l

echo "$0" "$@"
case $1 in
	(/etc/rc) ;;
	(*) exit 0;;
esac

sysctl net.inet.ip.portrange.reservedhigh=0

mount -wu /
mount -a
zfs mount -a
mount -al
swapon -aF /media/host/fstab.swap

service devfs start > /dev/null

kldload ipfw
ipfw add 65000 set 31 allow ip from any to any
xargs -L 1 ipfw add < /media/host/firewall

service motd start > /dev/null

(read host < /media/host/hostname; hostname $host)
service netif start > /dev/null

(umask 022; dmesg > /var/run/dmesg.boot)
