#!/bin/sh
[ "${1+1}" ] || exec csh -l

echo "$0" "$@"
case $1 in
	(/etc/rc) ;;
	(*) exit 0;;
esac

mount -wu /
mount -a
zfs mount -a
mount -al
swapon -aF /media/host/fstab.swap

(umask 022; dmesg > /var/run/dmesg.boot)

service motd start > /dev/null

(read host < /media/host/hostname; hostname $host)
service netif start > /dev/null
