#!/bin/sh
[ "${1+1}" ] || exec csh -l
# no -eu, because failure probably bricks the system

[ "$1" = /etc/rc ] || exit 0

sysctl net.inet.ip.portrange.reservedhigh=0

mount -wu /
mount -a
zfs mount -a
mount -al
swapon -aF /media/host/fstab.swap

service devfs start > /dev/null

kldload pf
pfctl -ef /media/host/pf.conf

service motd start > /dev/null

(read host < /media/host/hostname; hostname $host)

# brings up localhost &c., magic
service netif start > /dev/null

for script in /media/host/after/*; do
	[ -f "$script" ] || continue
	. "$script"
done

(umask 022; dmesg > /var/run/dmesg.boot)
