#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
[ "${1+1}" ] || exec csh -l

case $1 in
(/etc/*)
	rc=/libexec${1#/etc} ;;
(*)
	rc=$1 ;;
esac

[ -f "$rc" ] || exit 0
exec "$rc" "$@"
