#!/bin/sh
[ "${1+1}" ] || exec csh -l
# no -eu, because failure probably bricks the system

[ "$1" = /etc/rc ] || exit 0

mount -wu /
mount -a
zfs mount -a
mount -al
swapon -a

for script in /media/host/after/* /libexec/after/*; do
	[ -f "$script" ] || continue
	. "$script"
done

(umask 022; dmesg > /var/run/dmesg.boot)
